config/routes.rb
Rails.application.routes.draw do
  get 'schedules/index'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, :controllers=>{:sessions=>"session"}

  root 'welcome#index'
  resources :equipments, :lessons
  get 'schedule',:to=>'schedules#index', :as=>:create_schedule
  post 'schedule/create',:to=>'schedules#arrange_schedule', :as=>:arrange_schedule
end

app/models/equipment.rb
class Equipment < ActiveRecord::Base

  belongs_to :user ,autosave: true

end

app/controllers/equipments_controller.rb
class EquipmentsController < ApplicationController
    before_action :authenticate_user!, only: [:index, :new, :edit ]
    def index
      @equipments = current_user.equipments
    end

    def show
      @equipment = Equipment.find(params[:id])
    end

    def new
      #@equipment = current_user.equipments.new
      @equipment = current_user.equipments.new
    end

    def edit
      @equipment = Equipment.find(params[:id])
    end

    def create

      @equipment = Equipment.new(equipment_params)
      @equipment.user_id = current_user.id
      if @equipment.save
        redirect_to equipments_path
      else
        render action: :new
      end
    end

    def update
      @equipment = Equipment.find(params[:id])
      if @equipment.update_attributes(equipment_params)
        redirect_to equipments_path
      else
        render action: :edit
      end
    end

    def destroy
        Equipment.find(params[:id]).destroy
        redirect_to equipments_path
    end

    private
    def equipment_params
      params.require(:equipment).permit(:name, :max_class, :user_id, :desc)
    end
end

app/helpers/equipments_helper.rb
module EquipmentsHelper
end

app/views/equipments/_form.html.erb
<%= form_for (@equipment) do |f| %>
    <p>
      <%= f.label :name %><br>
      <%= f.text_field :name %>
    </p>

    <p>
      <%= f.label :max_class %><br>
      <%= f.text_field :max_class %>
    </p>
    <p>
      <%= f.label :desc %><br>
      <%= f.text_area :desc %>
    </p>

    <p>
      <%= f.submit %>
    </p>
<% end %>

app/views/equipments/edit.html.erb
<h1>Edit Class</h1>
<%= render partial: "form" %>

app/views/equipments/index.html.erb
<h1>All Equipments for User</h1>
<table>
  <tr>
    <th>Name</th>
    <th>Max Class</th>
    <th>Description</th>
    <th>Actions</th>
  </tr>

  <% @equipments.each do |equipment| %>
      <tr>
        <td><%= equipment.name %></td>
        <td><%= equipment.max_class %></td>
        <td><%= equipment.desc%></td>
        <td>
            <%= link_to 'Edit', edit_equipment_path(equipment) %>
            <%= link_to 'Delete', equipment,
                      method: :delete,
                      data: { confirm: 'Are you sure?' } %>
        </td>
      </tr>
  <% end %>
</table>
<p>
  <%= link_to 'Add New Equipment', new_equipment_path %>
</p>

app/views/equipments/new.html.erb
<h1>New Equipment</h1>

<%= form_for (@equipment), url: equipments_path do |f| %>
    <p>
      <%= f.label :name %><br>
      <%= f.text_field :name %>
    </p>

    <p>
      <%= f.label :max_class %><br>
      <%= f.text_field :max_class %>
    </p>
    <p>
      <%= f.label :desc %><br>
      <%= f.text_area :desc %>
    </p>

    <p>
      <%= f.submit %>
    </p>
<% end %>

app/views/equipments/show.html.erb
<h1>Equipment Details</h1>
<p>
  <%= @equipment.name %>
</p>
<p>
  <%= @equipment.max_class %>
</p>
<p>
  <%= @equipment.desc %>
</p>