config/routes.rb
Rails.application.routes.draw do
  get 'schedules/index'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, :controllers=>{:sessions=>"session"}

  root 'welcome#index'
  resources :equipments, :lessons
  get 'schedule',:to=>'schedules#index', :as=>:create_schedule
  post 'schedule/create',:to=>'schedules#arrange_schedule', :as=>:arrange_schedule
end

app/views/shared/_footer.html.erb
<!-- FOOTER -->
<footer>
  <div class="container">
    <div class="row">
      <div class="col-md-8">
        <h3>Need Help?</h3>
        <div class="clearfix"></div>
        <!--<p>
          Call Us at 866-332-7134 or <br>
          Email Us at <a href="#">xxx@s.com</a>
        </p>-->
      </div>

      <div class="col-md-4 terms">
        <p>SaltoSchedule. All Rights Reserved.</p>

       <!-- <ul class="termsList">
          <li><a href="#">Privacy Policy</a></li>
          <li><a href="#">Terms & Conditions</a></li>
        </ul>-->
      </div>
    </div>
  </div>
</footer>

app/views/shared/_header.html.erb
<!-- HEADER -->
<header>
  <nav class="navbar navbar-default" role="navigation">
    <div class="container">
      <div class="navbar-header">

        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>

        <a href="#"><h1>SaltoSchedule</h1></a>

      </div>

      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav  navbar-right">
          <li><%= link_to('Classes', lessons_path) %></li>
          <li><%= link_to('Equipments', equipments_path)%></li>
          <li><%= link_to('Schedule',create_schedule_path)%></li>
          <li><a href="#">About</a></li>

          <% if user_signed_in? %>
              <li>
                <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>
              </li>
          <% else %>
              <li>
                <%= link_to('Login', new_user_session_path)  %>
              </li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
</header>