config/routes.rb
Rails.application.routes.draw do
  get 'schedules/index'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, :controllers=>{:sessions=>"session"}

  root 'welcome#index'
  resources :equipments, :lessons
  get 'schedule',:to=>'schedules#index', :as=>:create_schedule
  post 'schedule/create',:to=>'schedules#arrange_schedule', :as=>:arrange_schedule
end

app/models/lesson.rb
class Lesson < ActiveRecord::Base
  belongs_to :user ,autosave: true
end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController


  before_action :authenticate_user!, only: [:index, :new, :edit ]
  #before_action :set_lesson, only: [:show, :edit, :update, :destroy]


  before_filter :get_json_variables, only: [:index, :edit, :new]
  def index
    @lessons    = current_user.lessons
    @equipments = current_user.equipments
  end

  def show
    @lesson = Lesson.find(params[:id])
  end

  def new
    #@lesson = current_user.lessons.new
    @equipments = current_user.equipments
    @lesson = current_user.lessons.new
  end

  def edit
    @equipments = current_user.equipments
    @lesson = Lesson.find(params[:id])
  end

  def create

    @lesson = Lesson.new(lesson_params)
    @lesson.user_id = current_user.id
    @lesson.schedule_repeat = params[:schedule_repeat]
    #create json format for hash
    #warm up
    warm_up = Hash.new
    warm_up[:equipment] =  params[:warmup_event]
    warm_up[:duration] = params[:warmup_duration]

    #condititioning
    conditioning = Hash.new
    conditioning[:equipment] = params[:conditioning_event]
    conditioning[:duration]  = params[:conditioning_duration]
    #events
    events = Array.new
    for i  in 0...params[:events].length
       event_data = Hash.new
      event_data[:equipment] = params[:events][i]
      event_data[:min_use_duration] =params[:event_min_duration][i]
      event_data[:max_use_duration] =params[:event_max_duration][i]
      event_data[:total_use_duration] = params[:event_duration][i]
      events.push(event_data)
    end

    #start and end time

    start_time = Hash.new
    end_time = Hash.new


    week_day = ['mon','tue','wed','thu','fri','sat','sun']
    for day in 0..6
      if(!params[:chk_schedule[day]].present?)
        first_key = week_day[day]+'(4i)'
        second_key = week_day[day]+'(5i)'
        start_time[day]= params[:start_time][first_key].to_i* 60+ params[:start_time][second_key].to_i
        end_time[day]  = params[:end_time][first_key].to_i* 60+ params[:end_time][second_key].to_i
      end
    end


    @lesson.warm_up = warm_up.to_json
    @lesson.conditioning = conditioning.to_json
    @lesson.start_time = start_time.to_json
    @lesson.end_time = end_time.to_json
    @lesson.events =events.to_json


    if @lesson.save
      redirect_to lessons_path
    else
      render action: :new
    end
  end

  def update
    @lesson = Lesson.find(params[:id])

    @lesson.schedule_repeat = params[:schedule_repeat]
    #create json format for hash
    warm_up = Hash.new
    warm_up[:equipment] =  params[:warmup_event]
    warm_up[:duration] = params[:warmup_duration]

    conditioning = Hash.new
    conditioning[:equipment] = params[:conditioning_event]
    conditioning[:duration]  = params[:conditioning_duration]

    events = Array.new
    for i  in 0...params[:events].length
      event_data = Hash.new
      event_data[:equipment] = params[:events][i]
      event_data[:min_use_duration] =params[:event_min_duration][i]
      event_data[:max_use_duration] =params[:event_max_duration][i]
      event_data[:total_use_duration] = params[:event_duration][i]
      events.push(event_data)
    end

    #start and end time

    start_time = Hash.new
    end_time = Hash.new


    week_day = ['mon','tue','wed','thu','fri','sat','sun']
    for day in 0..6

      if(params[:chk_schedule][week_day[day].to_sym].to_i==1)
        first_key = week_day[day]+'(4i)'
        second_key = week_day[day]+'(5i)'
        start_time[day]= params[:start_time][first_key].to_i* 60+ params[:start_time][second_key].to_i
        end_time[day]  = params[:end_time][first_key].to_i* 60+ params[:end_time][second_key].to_i
      else
        start_time[day]= 0
        end_time[day]  = 0
      end
      #start_time[day] = params[:chk_schedule][week_day[day]]
    end

    @lesson.warm_up = warm_up.to_json
    @lesson.conditioning = conditioning.to_json
    @lesson.start_time = start_time.to_json
    @lesson.end_time = end_time.to_json
    @lesson.events =events.to_json

    if @lesson.update_attributes(lesson_params)
      redirect_to lessons_path
    else
      render action: :edit
    end
  end

  def destroy
    Lesson.find(params[:id]).destroy
    redirect_to lessons_path
  end

  private
  def lesson_params
    params.require(:lesson).permit( :title, :user_id,  :instructor, :schedule_repeat, :warm_up, :conditioning, :start_time, :end_time,:events)
  end

  def get_json_variables
    #const durations
    @durations = Hash.new
    @durations[15] = "15 Minutes"
    @durations[30] = "30 Minutes"
    @durations[45] = "45 Minutes"
    @durations[60] = "60 Minutes"
    @durations[75] = "75 Minutes"
    @durations[90] = "90 Minutes"
    @durations[105] = "105 Minutes"
    @durations[120] = "120 Minutes"
    @durations[135] = "135 Minutes"
    @durations[150] = "150 Minutes"
    @durations[165] = "165 Minutes"
    @durations[180] = "180 Minutes"
    @durations[195] = "195 Minutes"
    @durations[210] = "210 Minutes"
    @durations[225] = "225 Minutes"

    #const timeline
    @times = Hash.new
    @times[15] = "15 Minutes"
    @times[30] = "30 Minutes"
    @times[45] = "45 Minutes"
    @times[60] = "60 Minutes"
    @times[75] = "75 Minutes"
    @times[90] = "90 Minutes"
    @times[105] = "105 Minutes"
    @times[120] = "120 Minutes"
    @times[135] = "135 Minutes"
    @times[150] = "150 Minutes"
    @times[165] = "165 Minutes"
    @times[180] = "180 Minutes"
    @times[195] = "195 Minutes"
    @times[210] = "210 Minutes"
    @times[225] = "225 Minutes"

    #schule repeat
    @repeat_interval = Hash.new
    @repeat_interval[1] = "Every Week"
    @repeat_interval[2] = "Every 2Weeks"

    #schedule_duration

    @schedule_duration = Hash.new
    @schedule_duration[12] = "12 Weeks"
    @schedule_duration[13] = "13 Weeks"

    @timeslot_intervals = Hash.new
    @timeslot_intervals[15] = "15 Minutes"
    @timeslot_intervals[20] = "20 Minutes"
    @timeslot_intervals[30] = "30 Minutes"
    @timeslot_intervals[45] = "45 Minutes"
    @timeslot_intervals[60] = "1 Hour"

  end
end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/views/lessons/_form.html.erb
<%= form_for(@lesson) do |f| %>

  <% if @lesson.errors.any? %>
    <div id="error_explanation">
      <h2>%<%= pluralize(@lesson.errors.count, "error") %> prohibited this lesson from being saved:</h2>

      <ul>
      <% @lesson.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <!--form to add/edit a lesson -->
    <%

    %>

  <div class="form-controls">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="form-controls">
     <%= f.label :instructor %><br>
     <%= f.text_field :instructor %>
  </div>
  <div class="form-controls">
    <%
       if(!@lesson.start_time.nil?)
            start_time = JSON(@lesson.start_time)
       end

       if(!@lesson.end_time.nil?)
            end_time = JSON(@lesson.end_time)
       end
       week_day = ['mon','tue','wed','thu','fri','sat','sun']
    %>

    <table>
        <thead>
            <th>Class Times</th>
            <%
               index = 0
               week_day.each do |day|
                    if(!start_time.nil?)
                        checked= (start_time[index.to_s].to_i > 0)
                    else
                        checked = false
                    end
                   key = 'chk_schedule['+day+']'
            %>
            <th><%=check_box_tag key,1,checked, class:'chk_schedule' %></th>
            <%
               index = index + 1
               end
            %>
        </thead>
        <tbody>
            <tr id="start_row">
                <td>Start</td>
                <%
                   index = 0
                   week_day.each do |day|
                     if(!start_time.nil?)
                         hour    = start_time[index.to_s].to_i / 60
                         minute  = start_time[index.to_s].to_i % 60
                    else
                        hour = 9
                        minute = 0
                    end
                 %><td>
                  <%= time_select 'start_time', day, {:ampm => true, :minute_step=>15, :start_hour=>9, :end_hour =>21, :default => Time.now.change(:hour => hour, :min=> minute)}%>
                  </td>
              <%
                 index = index + 1
                 end

                %>
            </tr>
            <tr id="end_row">
              <td>End</td>
              <%
                 index = 0
                 week_day.each do |day|
                   if(!end_time.nil?)
                     hour    = end_time[index.to_s].to_i / 60
                     minute  = end_time[index.to_s].to_i % 60
                   else
                     hour = 9
                     minute = 0
                   end
              %><td>
                  <%= time_select 'end_time', day, {:ampm => true, :minute_step=>15, :start_hour=>9, :end_hour =>21, :default => Time.now.change(:hour => hour, :min=> minute)}%>
                  </td>
              <%
                 index = index + 1
                 end
              %>

            </tr>
        </tbody>
    </table>
  </div>
    <!--  class scheudle repeater -->
    <div class="form-controls">
      <p>
        <%= f.label :schedule_repeat %>
        <%= select_tag('schedule_repeat', options_from_collection_for_select(@repeat_interval, :first, :last, @lesson.schedule_repeat)) %>

      </p>
    </div>
    <!-- for warmup and conditioner -->
    <div class="form-controls">
      <table>

        <tbody>
        <tr>
          <td>Warmup</td>
          <td>
            <%=
                if(!@lesson.warm_up.nil? and !@lesson.conditioning.nil?)
                    warmup = JSON(@lesson.warm_up)
                    conditioning = JSON(@lesson.conditioning)
                    def_warmup_equipment = warmup['equipment']
                    def_warmup_duration = warmup['duration']
                    def_con_equipment = conditioning['equipment']
                    def_con_duration = conditioning['duration']
                else
                  def_warmup_equipment = :first
                  def_warmup_duration = :first
                  def_con_equipment = :first
                  def_con_duration = :first
                end

                select_tag "warmup_event",options_from_collection_for_select(@equipments, 'id', 'name', def_warmup_equipment)
            %>
          </td>
          <td>
            At the beginning of the class for:
          </td>
          <td>
                <%= select_tag 'warmup_duration', options_from_collection_for_select(@durations, :first, :last, def_warmup_duration) %>
          </td>
        </tr>
        <tr>
          <td>Conditioning</td>
          <td>
            <%=
                select_tag "conditioning_event",options_from_collection_for_select(@equipments, 'id','name', def_con_equipment)
            %>
          </td>
          <td>
            At the end of the class for:
          </td>
          <td>
            <%= select_tag 'conditioning_duration', options_from_collection_for_select(@durations, :first, :last, def_con_duration) %>
          </td>
        </tr>
        </tbody>
      </table>
    </div>
    <!-- events -->
    <div class="form-controls">
      <table id="events_table">
        <thead>
        <th>Event</th>
         <th>Total Use Each Period(Set Above)</th>
        <th>Minimum Use Each Class</th>
        <th>Maximum Use Each Class</th>
        <th>Action</th>
        </thead>
        <tbody>
            <%
               if(@lesson.events)
                    events = JSON(@lesson.events)
                    total_events = events.length
               else
                    total_events = 1
               end

               #for i in 0...events.length
               for i in 0..total_events-1
                if(!events.nil?)
                    def_equipment       = events[i]['equipment']
                    def_total_duration  = events[i]['total_use_duration']
                    def_min_duration    = events[i]['min_use_duration']
                    def_max_duration    = events[i]['max_use_duration']
                else
                  def_equipment       = :first
                  def_total_duration  = 90
                  def_min_duration    = 15
                  def_max_duration    = 45
                end
            %>

        <tr class="event_row">
          <td>
            <%=  select_tag "events[]",options_from_collection_for_select(@equipments, 'id', 'name', def_equipment) %>
          </td>
          <td>
            <%= select_tag('event_duration[]', options_from_collection_for_select(@durations, :first, :last, def_total_duration)) %>
          </td>
          <td>
            <%= select_tag('event_min_duration[]', options_from_collection_for_select(@durations, :first, :last, def_min_duration)) %>
          </td>
          <td>
            <%= select_tag('event_max_duration[]', options_from_collection_for_select(@durations, :first, :last, def_max_duration)) %>
          </td>
          <td><a href="#" class="remove_event">Remove</a></td>
        </tr>
            <%
               end
            %>
        <tr>
          <td colspan="5" >
            <input type="button" name="add_stipulation" id="add_stipulation" value="Add Stipulation" style="float:right">
          </td>
        </tr>
        </tbody>
      </table>
    </div>
    <div class="form-controls">
        <%=link_to 'Create Schedule',create_schedule_path(:interval => 30), :id=>'create_schedule' %>
      <br/>
      <%= select_tag('schedule_duration', options_from_collection_for_select(@schedule_duration, :first, :last, '2')) %>
      <br/>
      <p>Time Slot Interval</p>
      <%= select_tag('timeslot_interval_form', options_from_collection_for_select(@timeslot_intervals, :first, :last, '30')) %>
    </div>
  <div class="actions">
    <%= f.submit %>

  </div>
<% end %>

app/views/lessons/_time_select.html.erb
<select>
  <option value="30">3:00PM</option>
</select>

app/views/lessons/edit.html.erb
<h1>Editing lesson</h1>

<%= render 'form' %>

<%= link_to 'Show', @lesson %> |
<%= link_to 'Back', lessons_path %>

app/views/lessons/index.html.erb
<h1>All Classes</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Instructor</th>
      <th>Repeats Every</th>
      <th>Equipments</th>
      <th>Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @lessons.each do |lesson| %>
      <tr>
        <td><%= lesson.title %></td>
        <td><%= lesson.instructor %></td>
        <td><%= lesson.schedule_repeat %></td>
        <td><%= lesson.events %></td>
        <td>
          <%= link_to 'Edit', edit_lesson_path(lesson) %>
          <%= link_to 'Delete', lesson, method: :delete, data: { confirm: 'Are you sure?' } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Lesson', new_lesson_path %>

app/views/lessons/new.html.erb
<h1>Add New Class</h1>

<%= render 'form' %>

<%= link_to 'Back', lessons_path %>

app/views/lessons/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_lesson_path(@lesson) %> |
<%= link_to 'Back', lessons_path %>